-- SOD One Platform V8 - Fundação SaaS / Supabase
create table if not exists public.organizations (id uuid primary key default gen_random_uuid(), name text not null, legal_name text, cnpj text, phone text, email text, city text, plan text not null default 'Plus', status text not null default 'active', created_at timestamptz not null default now());
create table if not exists public.organization_users (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null, role text not null default 'member', created_at timestamptz not null default now(), unique(organization_id, user_id));
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, phone text, email text, document text, created_at timestamptz not null default now());
create table if not exists public.vehicles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, customer_id uuid references public.customers(id) on delete set null, plate text, vehicle text, brand text, model text, year text, km numeric, status text default 'Entrada', notes text, created_at timestamptz not null default now());
create table if not exists public.service_orders (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, vehicle_id uuid references public.vehicles(id) on delete set null, customer_id uuid references public.customers(id) on delete set null, stage text not null default 'Entrada', complaint text, diagnosis text, total numeric default 0, created_at timestamptz not null default now(), closed_at timestamptz);
create table if not exists public.parts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, code text, description text not null, category text, manufacturer text, supplier text, location text, stock numeric default 0, min_stock numeric default 0, cost numeric default 0, sale_price numeric default 0, notes text, created_at timestamptz not null default now());
create table if not exists public.technical_base (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, vehicle_application text, vehicle_category text, service_category text, service_name text not null, sold_hours numeric default 0, hourly_rate numeric default 0, suggested_labor numeric default 0, complexity text, confidence text, procedure text, attention_points text, approval_criteria text, tools text, lessons text, common_parts text, similar_cases text, created_at timestamptz not null default now());
alter table public.organizations enable row level security; alter table public.organization_users enable row level security; alter table public.customers enable row level security; alter table public.vehicles enable row level security; alter table public.service_orders enable row level security; alter table public.parts enable row level security; alter table public.technical_base enable row level security;
